# Shared file included by the makefiles used to build packages.
# This contains various information needed by the makefiles,
# and is autogenerated by configure to include various
# necessary details.

# Tools needed:

CC = gcc
OBJDUMP = objdump
STRIP = strip
LDFLAGS =  -L/usr/local/lib -lSDL2 -L/usr/local/Cellar/libsamplerate/0.2.2/lib -lsamplerate -L/usr/local/opt/libpng/lib -lpng16 -L/usr/local/Cellar/fluid-synth/2.4.6/lib -lfluidsynth

# Package name and version number:

PROGRAM_PREFIX = chocolate-
PACKAGE = chocolate-doom
PACKAGE_NAME = Chocolate Doom
PACKAGE_STRING = Chocolate Doom 3.1.0
PACKAGE_TARNAME = chocolate-doom
PACKAGE_VERSION = 3.1.0

TARGET_OS = x64

# Documentation files to distribute with packages.

DOC_FILES = README.md        \
            README.Music.md  \
            COPYING.md       \
            NEWS.md

